### ISSUE TITLE
Add theme to the site

### ISSUE THREAD

**Issue by zenorocha** [dracula/limechat#1]
Hey @shmink,

I just wanted to let you know that this theme is now available in the site: https://draculatheme.com/limechat/

Cheers!

**Comment by shmink** [comment]
Not to be petty but I'm not in the contributors at the bottom of the page. Can that be fixed?

**Comment by zenorocha** [comment]
Ohhh I didn't notice that! That list is actually auto-generated from the GitHub commit list, so would you mind doing 2 commits? This way you'll show up first ;)
